### ISSUE TITLE
3.0.0-next.284 "Failed to render" warning in dev tools but components render

### ISSUE THREAD

**Issue by blackicellc** [sveltech/svelte-filerouter#566]
### Describe the bug

I updated to 3.0.0-next.284 from 3.0.0-next.283 and now there appears a "Failed to render" warning in dev tools but the components render perfectly. The warning: 
```
Failed to render  (src/routes/_module.svelte) within 5s. Ensure the parent component renders a <slot /> setTimeout handler*setActiveRoute@http://localhost:5173/node_modules/.vite/deps/@roxi_routify.js?v=1b113b30:3126:37
```
Perhaps I'm doing something wrong with the slots and the update reveals my mistake?

### Reproduction

To reproduce: 

- update an application using 3.0.0-next.283 to 3.0.0-next.284
- open dev tools
- navigate around the app to routes that on the file system have this structure:
```
src/routes
├── _module.svelte
├── about.svelte
├── cards
│   └── [id].svelte
├── cards-to-export.svelte
└── index.svelte
```
- The /cards/n paths all work as expected, however after a few seconds, in the dev tools the following warning appears:
```
Failed to render  (src/routes/_module.svelte) within 5s. Ensure the parent component renders a <slot /> setTimeout handler*setActiveRoute@http://localhost:5173/node_modules/.vite/deps/@roxi_routify.js?v=1b113b30:3126:37
```

For completeness, here is how the _module.svelte look and how the [id].svelte look (paired down for simplicity). Note: I also tried adding a _module.svelte with a slot at the root of cards (in case the warning's 'parent' referred to was the folder 'cards' and not the '_module.svelte' above 'cards.' The warning persisted. I hope this is enough information.

_module.svelte
```
<!-- Required; do not remove -->
<slot />
```

[id].svelte
```
<script>
        import {
		primaryCardId,
		hasLoaded,
	} from '../../lib/components/shared';
	import Inserted from '../../lib/components/card-related/inserted.svelte';

	export let currentCard;

</script>

<div class="container card-page">
	<!-- All three need to happen for correct values to cascade down -->
	{#if currentCard && $hasLoaded && $primaryCardId != 0}
		<Inserted id="{currentCard.id}" isFirst="{true}" />
	{/if}
</div>

<style lang="scss">
	.container {
		display: flex;
		flex-direction: column;
	}
</style>

```

### Logs

```shell
Warning:

Failed to render  (src/routes/_module.svelte) within 5s. Ensure the parent component renders a <slot /> setTimeout handler*setActiveRoute@http://localhost:5173/node_modules/.vite/deps/@roxi_routify.js?v=1b113b30:3126:37
```

### System Info

```shell
System:
    OS: macOS 15.5
    CPU: (12) arm64 Apple M2 Pro
    Memory: 68.69 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    npm: 10.4.0 - ~/.nvm/versions/node/v20.11.0/bin/npm
  npmPackages:
    @roxi/routify: ^3.0.0-next.284 => 3.0.0-next.284 
    svelte: ^4.0.0 => 4.2.20 
    vite: ^4.4.2 => 4.5.14
```

**Comment by jakobrosenberg** [comment]
Thanks for filing this, @blackicellc . Seeing as it's complaining about the root module, I think this is a bug.

Is it possible that you were clicking through links fast enough that a page didn't render before the url was changed?

**Comment by jakobrosenberg** [comment]
I've pushed `.285` which addresses the scenario I described. Let me know if that fixes your issue.

**Comment by blackicellc** [comment]
Hi @jakobrosenberg -- I just tried and this still appears, only now it appears on every page navigated to. I also wonder if it's associated with #565 ? Unfortunately, it's not from clicking quickly. I can sit on a page for a while, click on /about, and the error won't appear immediately. Instead it appears after about 5s.

Here's that warning:
```
App.svelte:8 Failed to render  (src/routes/_module.svelte) within 5s. Ensure the parent component renders a <slot /> at http://localhost:5173/node_modules/.vite/deps/@roxi_routify.js?v=a995a74b:3132:17
```

The about.svelte page is just this:
```
script>
	import { H1 } from '../lib/components/shared';

	const year = new Date().getFullYear();
</script>

<main>
	<div class="container">
		<div class="page about">
			<H1 text="About" />
                      ... more static markup with only the 'year' above interpolated in a copyright.

<style lang="scss">
	.container {
		.page {
			display: flex;
			flex-direction: column;
			align-items: flex-start;

			margin-left: auto;
			margin-right: auto;
      ...the rest of the scss without anything fancy. Not even any variables, etc.
```


and here's the tree of those files:
```
src/routes
├── _module.svelte
├── about.svelte
├── cards
│   ├── [id].svelte
│   └── _module.svelte
├── cards-to-export.svelte
└── index.svelte
```
And it's the same _module.svelte content in my original post above. Basically, just `<slot />`

I also tried putting text in the _module.svelte to see what happens. E.g. hello. It renders the 'hello', then the contents in the slot just fine below it. So, it *is* rendering in spite of the warning saying it failed to render.

(And I'm only sticking on this because both errors crept in during the same release) The route in the location bar gets changed to this: `localhost:5173/about;/about`

Thanks for the super speedy response, too! I wish I had better news to report!

**Comment by jakobrosenberg** [comment]
Any chance you can share a repo with me? Preferably a minimal.

**Comment by blackicellc** [comment]
Yeah, it crossed my mind. It's private (to another entity) repo, so I'll whip something up that replicates the issue w/o sharing any of their IP.

**Comment by blackicellc** [comment]
UPDATE: @jakobrosenberg I've shared a minimal repo with you. Let me know if you don't get the invite.

**Comment by jakobrosenberg** [comment]
Thanks for the PR. I found a small "issue" in your code which helped reveal and fix a bug in Routify.

In your example you create a no named router twice.

```html
<script context="module">
    import { Router, createRouter } from '@roxi/routify'
    import routes from '../.routify/routes.default.js'

    export const router = createRouter({ routes }) // first creation
</script>

<Router {routes} /> <!-- second creation -->
```

It should be
```html
<script context="module">
    import { Router, createRouter } from '@roxi/routify'
    import routes from '../.routify/routes.default.js'

    export const router = createRouter({ routes }) // first creation
</script>

<Router {router} /> <!-- use the router -->
```
Here we create a router and then use it the router component.

However, since both routers have the name "", Routify should have reused the first one you created. This has been fixed now, so technically you don't have to change anything, though I would recommend using `<Router {router} />`

**Comment by blackicellc** [comment]
Aha! Yes, nice catch. My brain was used to the semantics of a different library where one passes the routes to the Router component, so I was not seeing the 'r' at the end of 'router' but rather "seeing" an 's'! Thanks! And thanks for the super fast fix!
